server:
  port: 8081

api:
  base:
    path: /api/v1

spring:
  application:
    name: auth-service

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 36000000

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000}
  internal-secret: ${APP_INTERNAL_SECRET}
  activation:
    base-url: ${APP_BASE_URL}
  user-service:
    url: ${USER_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
