server:
  port: 8083

api:
  base:
    path: /api/v1

spring:
  application:
    name: integration-service

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 36000000

app:
  internal-secret: ${APP_INTERNAL_SECRET}
  auth:
    url: ${AUTH_URL}
  wholesale:
    url: ${WHOLESALE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF